### ISSUE TITLE
asset-path in imported CSS files are not handled properly

### ISSUE THREAD

**Issue by SebouChu** [tablecheck/dartsass-sprockets#8] opened 2023-03-14 11:17 UTC
Hello! I'm currently working on using Dart Sass on my present and future Rails projects.

First, thanks a lot for the work on this gem to allow us to use Dart Sass with Sprockets. Unfortunately, it seems that there is a breaking change when moving from `sassc-rails`.

I'm using Summernote as a WYSIWYG editor, using the `summernote-rails` gem to handle fonts etc. But it looks like `asset-path` are not handled properly and to make it work, I had to rename the summernote style files from `.css` to `.scss`. I had no problem like this with `sassc-rails`.

I created a Rails app which allows me to send you feedback and report any bug I encounter. A detailed issue about this is available here : https://github.com/SebouChu/dartsass-sprockets-app/issues/1

**Comment by johnnyshields** [comment] 2023-07-12 16:54
@SebouChu if I am reading correctly, it seems that dartsass-sprockets requires `.scss` to do SASS transformations, while `.css` is left used verbatim without SASS processing.

To me, this is a feature, not a bug. I would expect CSS to be unprocessed, while SCSS is processed. You will simply have to rename your files when migrating to use this library. I will add a note in the readme about this, and will close this ticket.

**Closed as completed by johnnyshields** 2023-07-12 16:54 UTC

**Comment by SebouChu** [comment] 2023-07-12 20:36
@johnnyshields The thing is, the file is actually CSS code, it's more about the fact that having css files with Sprockets helpers inside are broken and I was forced to change the extension to SCSS so that the file goes through Sprockets without any issue (no sass helpers)
